/**
 * Optional extras per team and per match that are not in the SkillCorner data.
 * Everything here is optional: a team without a logo gets a monogram badge and a
 * match without links simply shows no link.
 *
 * Crests are the clubs' own marks, used here only to identify the teams.
 */

import logos from "./logos.json";

/** SkillCorner team id -> crest image in /public/logos (generated by `make crests`). */
const TEAM_LOGOS = logos as Record<string, string>;

export function teamLogo(teamId: number): string | null {
  return TEAM_LOGOS[String(teamId)] ?? null;
}

export interface MatchLinks {
  /** Official highlights video (YouTube watch URL). */
  highlights?: string;
  /** Match report or match centre page. */
  report?: string;
}

/** SkillCorner match id -> external links */
const MATCH_LINKS: Record<number, MatchLinks> = {
  2006229: {
    highlights: "https://www.youtube.com/watch?v=3qfT9jBfdZQ",
    report: "https://aleagues.com.au/news/melbourne-city-macarthur-fc-max-caputo-match-report-goals-highlights-video-aleague-men-round-22/",
  },
  2017461: {
    highlights: "https://www.youtube.com/watch?v=xgAaEqw_SK4",
    report: "https://aleagues.com.au/news/melbourne-victory-auckland-fc-rogerson-goal-semi-final-leg-one-highlights-video/",
  },
};

export function matchLinks(matchId: number): MatchLinks {
  return MATCH_LINKS[matchId] ?? {};
}
